#ifndef DIFFERENTIATOR_ERRORS_H_INCLUDED
#define DIFFERENTIATOR_ERRORS_H_INCLUDED

enum DifferentiatorErrors
{
    NULL_POINTER_DIFF = -3,
    SYNTAX_ERROR_DIFF = -1,
    FILE_OPENING_ERROR_DIFF = -2,
    ALLOCATION_FAILURE_DIFF = -4,
    UNKNOWN_ERROR_DIFF = -57,
    FILE_READING_ERROR_DIFF = -6,
};


#endif