#ifndef DIFFERENTIATOR_ERRORS_H_INCLUDED
#define DIFFERENTIATOR_ERRORS_H_INCLUDED

enum DifferentiatorErrors
{
    SYNTAX_ERROR_DIFF = -1,
    FILE_OPENING_ERROR_DIFF = -2,
    NULL_POINTER_DIFF = -3,
    ALLOCATION_FAILURE_DIFF = -4,
    NO_INPUT_FILE = -5,
    FILE_READING_ERROR_DIFF = -6,
    CALCULATION_FAILURE = -7,
    DEGREE_IS_TOO_BIG = -8,
    TOKENISATION_FAILURE = -9,
    EMPTY_INPUT_STRING = -10,
    UNKNOWN_ERROR_DIFF = -57,
};


#endif